### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by vaibhav-1508** [technex-iit-bhu/CA_Frontend#11]
![Screenshot from 2023-10-17 18-52-45](https://github.com/technex-iit-bhu/CA_Frontend/assets/96713176/e6ec2f5e-1cc9-4df2-aaa1-185c2ee7b00d)

- [ ] Create cards for the podium 
- [ ] Create cards for of the users
- [ ] Create a scroll action for rest of the users
- [ ] Make API calls to fetch the Name, CA ID, points of the users

**Comment by vinfinity7** [comment]
assign me this @vaibhav-1508
