### ISSUE TITLE
Create a Login Page

### ISSUE THREAD

**Issue by Sweetdevil144** [technex-iit-bhu/CA_Frontend#24]
Need to create a full fledged Login Page. Need suggestions @vaibhav-1508 and @BabyElias for this

**Comment by shivansh-bhatnagar18** [comment]
Also a Register Page for the same

**Comment by Sweetdevil144** [comment]
@vaibhav-1508 assign me.

**Comment by BabyElias** [comment]
https://ca.technex.co.in/
Refer this for Registration & Login page fields.
