### ISSUE TITLE
Styling for FAQs Section

### ISSUE THREAD

**Issue by BabyElias** [technex-iit-bhu/CA_Frontend#26]
![image](https://github.com/technex-iit-bhu/CA_Frontend/assets/95405559/de0c9a86-cc5e-44ee-99b5-f41a33f49eaa)
The outlook for this section is ready, a few design elements need to be added.

**Comment by vinfinity7** [comment]
assign me this @vaibhav-1508

**Comment by vaibhav-1508** [comment]
@Sweetdevil144 and @shivansh-bhatnagar18 fix the accordian component
