### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by BabyElias** [technex-iit-bhu/CA_Frontend#4]
![image](https://github.com/technex-iit-bhu/CA_Frontend/assets/95405559/81c15a9a-c696-4d5e-acc7-fb9b65250f08)

**Comment by shivansh-bhatnagar18** [comment]
Please assign me this FAQ component of the homepage of the CA Portal

**Comment by shivansh-bhatnagar18** [comment]
Dear Authors, Please check the pull request #18
