### ISSUE TITLE
Connect the Login Page and Registration Page to the Backend

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [technex-iit-bhu/CA_Frontend#46]
- [ ] The User Creates his profile gets stored in the database
- [ ] The Login Page Checks for the Registered Users
- [ ] Also Register only when Password == Confirm Password

**Comment by shivansh-bhatnagar18** [comment]
@BabyElias @vaibhav-1508 Please Assign this issue to @Sweetdevil144. We'll be working on this

**Comment by Sweetdevil144** [comment]
On it !1
