### ISSUE TITLE
Leaderboard Page

### ISSUE THREAD

**Issue by vaibhav-1508** [technex-iit-bhu/CA_Frontend#63]
- [ ] Add black padding around the text as seen in design
![Screenshot from 2023-10-31 19-29-53](https://github.com/technex-iit-bhu/CA_Frontend/assets/96713176/d9596926-b759-4f4c-8355-f24569d8938f)
- [ ] Correct the font style and font weights
- [ ] Correct the designing of the leaderboard heading (Refer to the 12 line of the following file https://github.com/technex-iit-bhu/CA_Frontend/blob/master/src/components/abouttechnex.tsx)

Refer to the designs 
https://www.figma.com/file/n0SgLdEkL90TVrrCC0ShpL/CA-Portal?type=design&node-id=106-41&mode=design&t=UV4OnaWx14LfHPMS-0

**Comment by vaibhav-1508** [comment]
@vinfinity7

**Comment by StoneCoder123** [comment]
I am doing this one
