### ISSUE TITLE
Landing Design & About Technex

### ISSUE THREAD

**Issue by BabyElias** [technex-iit-bhu/CA_Frontend#7]
![image](https://github.com/technex-iit-bhu/CA_Frontend/assets/95405559/cf59d399-7235-439e-968a-8e32715dec30)

**Comment by vaibhav-1508** [comment]
Use this and transform it by 90 degree
https://chakra-ui.com/docs/components/icon

Also add bounce animation to the icon
https://tailwindcss.com/docs/animation#bounce
