### ISSUE TITLE
Carousel for Incentives Page

### ISSUE THREAD

**Issue by VAbhijith2003github** [technex-iit-bhu/CA_Frontend#9]
![image](https://github.com/technex-iit-bhu/CA_Frontend/assets/119759593/32c3282e-6f05-46d2-b943-fdcdb6f93d95)

- [ ] Make a card component for the carousel 
- [ ] Import the card component to the carousel component
- [ ] Add scrolling animation to the component along with the buttons

**Comment by StoneCoder123** [comment]
Please assign me this issue
